export enum textTypes {
  TITLE_BOLD = 'TITLE_BOLD', //24px
  TITLE_REGULAR = 'TITLE_REGULAR',
  TITLE_LIGHT = 'TITLE_LIGHT',
  TITLE_SEMI_BOLD = 'TITLE_SEMI_BOLD',
  SUB_TITLE_BOLD = 'TITLE_BOLD', //20px
  SUB_TITLE_REGULAR = 'TITLE_REGULAR',
  SUB_TITLE_LIGHT = 'TITLE_LIGHT',
  SUB_TITLE_SEMI_BOLD = 'TITLE_SEMI_BOLD',
  PARAGRAPH_BOLD = 'TITLE_BOLD', //14px
  PARAGRAPH_REGULAR = 'TITLE_REGULAR',
  PARAGRAPH_LIGHT = 'TITLE_LIGHT',
  PARAGRAPH_SEMI_BOLD = 'TITLE_SEMI_BOLD',
  PARAGRAPH_SMALL_BOLD = 'TITLE_BOLD', //10px
  PARAGRAPH_SMALL_REGULAR = 'TITLE_REGULAR',
  PARAGRAPH_SMALL_LIGHT = 'TITLE_LIGHT',
  PARAGRAPH_SEMI_BOLD = 'TITLE_SEMI_BOLD',

  BUTTON_BOLD = 'BUTTON_BOLD', //18px
  BUTTON_REGULAR = 'BUTTON_REGULAR',
  BUTTON_LIGHT = 'BUTTON_LIGHT',
  BUTTON_SEMI_BOLD = 'BUTTON_SEMI_BOLD',
}
